services:
  mariadb:
    image: mariadb:12.2
    container_name: "binbogami_mariadb"
    restart: "no"
    volumes:
      - "./var/volumes/mariadb:/var/lib/mysql"
    ports:
      - "3306:3306"
    env_file:
      - ".env.docker"
    networks:
      - "binbogami"
  mailcatcher:
    image: dockage/mailcatcher:0.9
    container_name: "binbogami_mailcatcher"
    restart: "no"
    ports:
      - "1080:1080"
      - "1025:1025"
    env_file:
      - ".env.docker"
    networks:
      - "binbogami"
  grafana:
    image: grafana/grafana:13.0
    container_name: "binbogami_grafana"
    restart: "no"
    volumes:
      - "./var/volumes/grafana:/var/lib/grafana"
    ports:
      - "3000:3000"
    env_file:
      - ".env.docker"
    networks:
      - "binbogami"
  loki:
    image: grafana/loki:3.7
    container_name: "binbogami_loki"
    restart: "no"
    volumes:
      - "./var/volumes/loki:/loki"
    ports:
      - "3100:3100"
    env_file:
      - ".env.docker"
    networks:
      - "binbogami"
networks:
  binbogami:
    name: "binbogami"
    external: true
