services:
  mariadb:
    image: mariadb:12.3
    container_name: "binbogami_mariadb"
    restart: "no"
    volumes:
      - "./var/volumes/mariadb:/var/lib/mysql"
    ports:
      - "3306:3306"
    env_file:
      - ".env.docker"
    networks:
      - "binbogami"
  mailcatcher:
    image: dockage/mailcatcher:0.9
    container_name: "binbogami_mailcatcher"
    restart: "no"
    ports:
      - "1080:1080"
      - "1025:1025"
    env_file:
      - ".env.docker"
    networks:
      - "binbogami"
  grafana:
    image: grafana/grafana:13.0
    container_name: "binbogami_grafana"
    restart: "no"
    volumes:
      - "./var/volumes/grafana:/var/lib/grafana"
    ports:
      - "3000:3000"
    env_file:
      - ".env.docker"
    networks:
      - "binbogami"
  loki:
    image: grafana/loki:3.7
    container_name: "binbogami_loki"
    restart: "no"
    volumes:
      - "./var/volumes/loki:/loki"
    ports:
      - "3100:3100"
    env_file:
      - ".env.docker"
    networks:
      - "binbogami"
  redis:
    image: redis:8.10-alpine
    container_name: "binbogami_redis"
    restart: "no"
    volumes:
      - "./var/volumes/redis:/data"
    ports:
      - "6379:6379"
    env_file:
      - ".env.docker"
    networks:
      - "binbogami"
  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: "binbogami_seaweedfs"
    restart: "no"
    command: "server -s3 -dir=/data -s3.port=8333 -s3.allowEmptyFolder=true"
    volumes:
      - "./var/volumes/seaweedfs:/data"
    ports:
      - "8333:8333"
      - "8888:8888"
      - "9333:9333"
    env_file:
      - ".env.docker"
    networks:
      - "binbogami"
networks:
  binbogami:
    name: "binbogami"
    external: true
